name: basic_http_interceptor
description: HTTP Interceptors for Beginners, Logging, Headers, Proxies, and Hooks.
version: 0.0.3
repository: https://github.com/huanguan1978/basic_http_interceptor

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  http_interceptor: ^2.0.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
